Update Gitleaks workflow for master branchs

diff --git a/.github/workflows/gitleaks.yml b/.github/workflows/gitleaks.yml
--- a/.github/workflows/gitleaks.yml
+++ b/.github/workflows/gitleaks.yml
@@ -19,7 +19,16 @@ jobs:
 
       - name: Install Gitleaks
         run: |
+          # Download Gitleaks
           curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.9.0/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
+          
+          # Check if the download was successful
+          if [ ! -f /usr/local/bin/gitleaks ]; then
+            echo "Gitleaks download failed!"
+            exit 1
+          fi
+
+          # Make it executable
           chmod +x /usr/local/bin/gitleaks
 
       - name: Verify Gitleaks Installation
